name: R Package CI

on:
  push:
    branches: [main, master]  # Run CI when code is pushed to main/master
  pull_request:
    branches: [main, master]  # Run CI on pull requests to main/master

jobs:
  test-r-package:
    runs-on: ubuntu-latest  # Use Linux environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Install latest R version

      - name: Install system dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "testthat", "covr", "devtools", "httr", "jsonlite", "dplyr", "ggplot2", "ggmap", "ggrepel", "stringdist", "tibble"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run tests
        run: Rscript -e 'devtools::test()'  # Run unit tests

      - name: Run code coverage
        run: Rscript -e 'covr::package_coverage()'  # Check test coverage

      - name: Upload coverage to Codecov
        run: Rscript -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results (if failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/testthat/

      - name: Upload R CMD check results (if failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: R-CMD-check-results
          path: check/
