name: R Package CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-r-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "testthat", "covr", "devtools", "httr", "jsonlite", "dplyr", "ggplot2", "ggmap", "ggrepel", "stringdist", "tibble"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Build and Install package
        run: |
          R CMD build .
          R CMD INSTALL *.tar.gz
        continue-on-error: true

      - name: Run R CMD check
        run: Rscript -e 'devtools::check(error_on = "never")'
        continue-on-error: true

      - name: Run tests
        run: Rscript -e 'devtools::test()'
        continue-on-error: true

      - name: Run code coverage
        run: Rscript -e 'covr::codecov()'
        continue-on-error: true

      - name: Upload test results (if failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/testthat/

      - name: Upload R CMD check results (if failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check/

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report.html
